[workspace]
resolver = "3"
members = [
    "crates/engine",
    "crates/game",
    "crates/tools",
    "crates/debug",
    "tests",
]
default-members = [
    "crates/engine",
    "crates/game",
    "tests",
]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
game_engine = { path = "crates/engine", version = "0.1.0" }
vulkano = { version = "0.35", default-features = true }
winit = { version = "0.30", default-features = true }
naga = { version = "30", default-features = false, features = ["glsl-in", "spv-out", "wgsl-in"] }
fontdue = { version = "0.9", default-features = true }
glam = { version = "0.33", default-features = true }
