[package]
name = "game_debug"
version.workspace = true
edition.workspace = true

[dependencies]
fontdue.workspace = true
game.workspace = true
game_engine.workspace = true
glam.workspace = true
png.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
vulkano.workspace = true
winit.workspace = true

[lib]
name = "game_debug"
path = "src/lib.rs"

[[bin]]
name = "game_debug"
path = "src/main.rs"
